"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginUserController = exports.deleteUserController = exports.getByIdUserController = exports.getAllUserController = exports.createUserController = exports.loginUserUseCase = exports.deleteUserUseCase = exports.getByIdUserUseCase = exports.getAllUseCase = exports.createUserUseCase = exports.mysqlUserRepository = exports.encryptationService = void 0;
const CreateUserUseCase_1 = require("../application/CreateUserUseCase");
const DeleteUserUseCase_1 = require("../application/DeleteUserUseCase");
const GetAllUserUseCase_1 = require("../application/GetAllUserUseCase");
const GetByIdUserUseCase_1 = require("../application/GetByIdUserUseCase");
const LoginUserUseCase_1 = require("../application/LoginUserUseCase");
const CreateUserController_1 = require("./controllers/CreateUserController");
const DeleteUserController_1 = require("./controllers/DeleteUserController");
const GetAllUserController_1 = require("./controllers/GetAllUserController");
const GetByIdUserController_1 = require("./controllers/GetByIdUserController");
const LoginUserController_1 = require("./controllers/LoginUserController");
const MysqlUserRepository_1 = require("./MysqlUserRepository");
const cifradoUseCase_1 = require("../application/services/cifradoUseCase");
exports.encryptationService = new cifradoUseCase_1.EncryptionService();
exports.mysqlUserRepository = new MysqlUserRepository_1.MysqlUserRepository();
exports.createUserUseCase = new CreateUserUseCase_1.CreateUserUseCase(exports.mysqlUserRepository, exports.encryptationService);
exports.getAllUseCase = new GetAllUserUseCase_1.GetAllUserUseCase(exports.mysqlUserRepository);
exports.getByIdUserUseCase = new GetByIdUserUseCase_1.GetByIdUserUseCase(exports.mysqlUserRepository);
exports.deleteUserUseCase = new DeleteUserUseCase_1.DeleteUserUseCase(exports.mysqlUserRepository);
exports.loginUserUseCase = new LoginUserUseCase_1.LoginUserUseCase(exports.mysqlUserRepository);
exports.createUserController = new CreateUserController_1.CreateUserController(exports.createUserUseCase);
exports.getAllUserController = new GetAllUserController_1.GetAllUserController(exports.getAllUseCase);
exports.getByIdUserController = new GetByIdUserController_1.GetByIdUserController(exports.getByIdUserUseCase);
exports.deleteUserController = new DeleteUserController_1.DeleteUserController(exports.deleteUserUseCase);
exports.loginUserController = new LoginUserController_1.LoginUserController(exports.loginUserUseCase);
